<b>About the dataset</b>

1) Asthma: 222 samples<br>
2) Bronchiectasis: 54 samples<br>
3) COPD: 57 samples<br>
4) Healthy: 35 samples<br>


In [2]:
from __future__ import division 
import numpy as np
import scipy
from scipy.stats import pearsonr
import scipy.signal as sps
import scipy.io.wavfile as wf
from vmdpy import VMD
import glob
import os
import librosa as lib
from librosa import feature as libf
import augly.audio as audaugs
import matplotlib.pyplot as plt 
import soundfile as sf
from gammatone import gtgram

from scipy import fft, arange
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile
import os

import pywt
import pywt.data

Augmentation

In [4]:
sr=4000

In [10]:
def aug(y):
    y_t_shift = t_shift(y)
    y_p_shift = pitch_shift(y)
    y_s_change = speed_change(y)
    return y_t_shift, y_p_shift, y_s_change

In [7]:
def t_shift(y):
    y_shift_r = y[:-2*sr]
    return y_shift_r

In [8]:
def pitch_shift(y):
    return lib.effects.pitch_shift(y, sr=sr, bins_per_octave=12, n_steps=4)

In [9]:
def speed_change(y):
    return lib.effects.time_stretch(y, rate=1.2)
    

In [15]:
y, sr=lib.load("CollectedDataset/Asth/3_AAL_W_A.wav", sr=sr)
y_t, y_p, y_s = aug(y)
display(y_t, y_p, y_s)

array([0.0000000e+00, 0.0000000e+00, 6.1035156e-05, ..., 1.3989258e-01,
       1.4184570e-01, 1.4352417e-01], dtype=float32)

array([ 0.00384416,  0.00454657,  0.0040671 , ..., -0.05487629,
       -0.05056215, -0.05875032], dtype=float32)

array([0.00642918, 0.00680945, 0.0072204 , ..., 0.07607242, 0.0787341 ,
       0.08085155], dtype=float32)

In [17]:
for filename in glob.glob('CollectedDataset\Bron\*.wav'):
    y,sr=lib.load(filename, sr=4000)
    y_t, y_p, y_s = aug(y)
    file=filename.split("\\")[2].split(".")[0]
    
    print(file)
    sf.write("CollectedDataset\Bron_Aug\ "+ file+".wav", y, sr)
    sf.write("CollectedDataset\Bron_Aug\ "+ file+"_time_shift.wav", y_t, sr)
    sf.write("CollectedDataset\Bron_Aug\ "+ file+"_pitch_shift.wav", y_p, sr)
    sf.write("CollectedDataset\Bron_Aug\ "+ file+"_speed_change.wav", y_s, sr)

12_PAL_CR_BR
12_PBL_CR_BR
12_PML_CR_BR
17_PAL_CR_BR
17_PAR_CR_BR
17_PBR_CR_BR
17_PMB_CR_BR
17_PML_CR_BR
17_PMR_CR_BR
19_PBL_CR_BR
19_PML_CR_BR
23_AAL_CR_BR
23_PB_CR_BRL
23_PML_CR_BR
23_PMR_CR_BR
26_PAR_CR_BR
26_PMR_CR_BR
27_PAL_CR_BR
27_PAR_CR_BR
27_PBL_CR_BR
27_PBR_CR_BR
27_PML_CR_BR
27_PMR_CR_BR
32_PAL_CR_BR
32_PAR_CR_BR
32_PBL_CR_BR
32_PBR_CR_BR
32_PML_CR_BR
32_PMR_CR_BR
48_PAL_CR_BR
48_PAR_CR_BR
48_PBL_CR_BR
48_PBR_CR_BR
48_PML_CR_BR
48_PMR_CR_BR
50_PAL_CR_BR
50_PAR_CR_BR
50_PBL_CR_BR
50_PML_CR_BR
65_PAR_B
65_PBR_B
67_PBL_C_B
67_PML_C_B
6_PAL_CR_BR
6_PAR_CR_BR
6_PBL_CR_BR
6_PBR_CR_BR
6_PML_CR_BR
6_PMR_CR_BR
79_PAL_C_B
79_PAR_C_B
79_PBR_C_B
79_PML_C_B
79_PMR_C_B


In [18]:
for filename in glob.glob('CollectedDataset\COPD\*.wav'):
    y,sr=lib.load(filename, sr=4000)
    y_t, y_p, y_s = aug(y)
    file=filename.split("\\")[2].split(".")[0]
    
    print(file)
    sf.write("CollectedDataset\COPD_Aug\ "+ file+".wav", y, sr)
    sf.write("CollectedDataset\COPD_Aug\ "+ file+"_time_shift.wav", y_t, sr)
    sf.write("CollectedDataset\COPD_Aug\ "+ file+"_pitch_shift.wav", y_p, sr)
    sf.write("CollectedDataset\COPD_Aug\ "+ file+"_speed_change.wav", y_s, sr)

34_PAL_W_C
34_PAR_W_C
34_PMR_W_C
36_AAR_W_C
36_PAL_W_C
36_PAR_W_C
36_PBL_W_C
36_PBR_W_C
39_AAR_W_C
39_PAL_W_C
39_PAR_W_C
39_PBL_W_C
39_PBR_W_C
39_PML_W_C
39_PMR_W_C
42_AAR_W_C
42_PAL_W_C
42_PAR_W_C
42_PBL_W_C
42_PBR_W_C
42_PML_W_C
42_PMR_W_C
45_PBL_C_C
45_PML_C_C
45_PMR_C_C
46_PAL_W_C
46_PAR_W_C
46_PBL_W_C
46_PBR_W_C
46_PML_W_C
46_PMR_W_C
68_PAL_W_C
68_PAR_W_C
68_PBL_W_C
68_PBR_W_C
68_PML_W_C
68_PMR_W_C
76_AAR_W_C
76_PAL_W_C
76_PAR_W_C
76_PBL_W_C
76_PBR_W_C
76_PML_W_C
76_PMR_W_C
7_PAL_CR_CO
7_PAR_CR_CO
7_PBL_CR_CO
7_PBR_CR_CO
7_PML_CR_CO
7_PMR_CR_CO
83_PAR_C_C
83_PBR_C_C
83_PMR_C_C
87_AAR_W_C
87_PAR_W_C
87_PML_W_C
87_PMR_W_C


In [15]:
for filename in glob.glob('Audio files\COPD\*.wav'):
    y,sr=lib.load(filename, sr=4000)
    y_t, y_p, y_s = aug(y)
    file=filename.split("\\")[2].split(".")[0]
    
    print(file)
    sf.write("Audio files aug\COPD\ "+ file+".wav", y, sr)
    sf.write("Audio files aug\COPD\ "+ file+"_time_shift.wav", y_t, sr)
    sf.write("Audio files aug\COPD\ "+ file+"_pitch_shift.wav", y_p, sr)
    sf.write("Audio files aug\COPD\ "+ file+"_speed_change.wav", y_s, sr)

104_1b1_Al_sc_Litt3200
104_1b1_Ar_sc_Litt3200
104_1b1_Ll_sc_Litt3200
104_1b1_Lr_sc_Litt3200
104_1b1_Pl_sc_Litt3200
104_1b1_Pr_sc_Litt3200
106_2b1_Pl_mc_LittC2SE
106_2b1_Pr_mc_LittC2SE
107_2b3_Al_mc_AKGC417L
107_2b3_Ar_mc_AKGC417L
107_2b3_Ll_mc_AKGC417L
107_2b3_Lr_mc_AKGC417L
107_2b3_Pl_mc_AKGC417L
107_2b3_Pr_mc_AKGC417L
107_2b3_Tc_mc_AKGC417L
107_2b4_Al_mc_AKGC417L
107_2b4_Ar_mc_AKGC417L
107_2b4_Ll_mc_AKGC417L
107_2b4_Lr_mc_AKGC417L
107_2b4_Pl_mc_AKGC417L
107_2b4_Pr_mc_AKGC417L
107_2b4_Tc_mc_AKGC417L
107_2b5_Al_mc_AKGC417L
107_2b5_Ar_mc_AKGC417L
107_2b5_Ll_mc_AKGC417L
107_2b5_Lr_mc_AKGC417L
107_2b5_Pl_mc_AKGC417L
107_2b5_Pr_mc_AKGC417L
107_2b5_Tc_mc_AKGC417L
107_3p2_Al_mc_AKGC417L
107_3p2_Ar_mc_AKGC417L
107_3p2_Ll_mc_AKGC417L
107_3p2_Lr_mc_AKGC417L
107_3p2_Pl_mc_AKGC417L
107_3p2_Pr_mc_AKGC417L
107_3p2_Tc_mc_AKGC417L
109_1b1_Al_sc_Litt3200
109_1b1_Ar_sc_Litt3200
109_1b1_Ll_sc_Litt3200
109_1b1_Lr_sc_Litt3200
109_1b1_Pl_sc_Litt3200
109_1b1_Pr_sc_Litt3200
110_1b1_Pr_sc_Meditron
110_1p1_Al_

KeyboardInterrupt: 

In [19]:
for filename in glob.glob('CollectedDataset\Hlth\*.wav'):
    y,sr=lib.load(filename, sr=4000)
    y_t, y_p, y_s = aug(y)
    file=filename.split("\\")[2].split(".")[0]
    
    print(file)
    sf.write("CollectedDataset\Hlth_Aug\ "+ file+".wav", y, sr)
    sf.write("CollectedDataset\Hlth_Aug\ "+ file+"_time_shift.wav", y_t, sr)
    sf.write("CollectedDataset\Hlth_Aug\ "+ file+"_pitch_shift.wav", y_p, sr)
    sf.write("CollectedDataset\Hlth_Aug\ "+ file+"_speed_change.wav", y_s, sr)

102_1b1_Ar_sc_Meditron
121_1b1_Tc_sc_Meditron
121_1p1_Tc_sc_Meditron
123_1b1_Al_sc_Meditron
125_1b1_Tc_sc_Meditron
126_1b1_Al_sc_Meditron
127_1b1_Ar_sc_Meditron
136_1b1_Ar_sc_Meditron
143_1b1_Al_sc_Meditron
144_1b1_Al_sc_Meditron
144_1b1_Tc_sc_Meditron
152_1b1_Al_sc_Meditron
153_1b1_Al_sc_Meditron
159_1b1_Al_sc_Meditron
159_1b1_Ar_sc_Meditron
159_1b1_Ll_sc_Meditron
159_1b1_Pr_sc_Meditron
171_1b1_Al_sc_Meditron
179_1b1_Al_sc_Meditron
179_1b1_Tc_sc_Meditron
182_1b1_Tc_sc_Meditron
183_1b1_Pl_sc_Meditron
183_1b1_Tc_sc_Meditron
184_1b1_Ar_sc_Meditron
187_1b1_Ll_sc_Meditron
194_1b1_Lr_sc_Meditron
194_1b1_Pr_sc_Meditron
202_1b1_Ar_sc_Meditron
208_1b1_Ll_sc_Meditron
209_1b1_Tc_sc_Meditron
214_1b1_Ar_sc_Meditron
217_1b1_Tc_sc_Meditron
224_1b1_Tc_sc_Meditron
224_1b2_Al_sc_Meditron
225_1b1_Pl_sc_Meditron
